call:
  name: Place DSS VoIP call
  description: Send TTS via DSS VoIP add-on to a SIP URI.
  fields:
    phone_number:
      required: true
      example: "+19070000000"
      selector:
        text:
          type: tel
    message_tts:
      required: true
      example: "This is a test."
      selector:
        text:
          multiline: true
    host:
      required: false
      default: "192.168.1.1"
      selector:
        text: {}
    port:
      required: false
      default: 5060
      selector:
        number:
          min: 1
          max: 65535
          mode: box
    addon_slug:
      required: false
      default: "89275b70_dss_voip"
      selector:
        text: {}
